"""UI copy for zh / en."""

from __future__ import annotations

from typing import Literal

Lang = Literal["zh", "en"]

STRINGS: dict[Lang, dict[str, str]] = {
    "zh": {
        "window_title": "try-working-hard",
        "app_subtitle": "",
        "seg_control": "控制面板",
        "seg_log": "紀錄",
        "theme_appearance": "外觀",
        "theme_appearance_dark": "深色",
        "theme_appearance_light": "淺色",
        "theme_status_dark": "深色主題",
        "theme_status_light": "淺色主題",
        "lang_ui": "介面語言",
        "dashboard": "主控台",
        "interval_label": "間隔",
        "interval_presets_caption": "快速間隔",
        "interval_preset_30s": "30s",
        "interval_preset_1m": "1m",
        "interval_preset_5m": "5m",
        "interval_preset_10m": "10m",
        "autostart_switch_title": "隨 Windows 啟動",
        "autostart_switch_hint": "登入 Windows 時自動執行，並在系統匣中啟動。",
        "autostart_not_windows": "（僅支援 Windows。）",
        "autostart_requires_tray": "（需安裝 pystray 系統匣。）",
        "log_tray_start_hidden": "以系統匣模式執行（主視窗已隱藏）。",
        "interval_unit_min": "分鐘",
        "interval_unit_sec": "秒",
        "interval_hint_min": "≥ 0.1，可小數（鍵盤／滑鼠無輸入須達此時間）",
        "interval_hint_sec": "≥ 6，可小數（鍵盤／滑鼠無輸入須達此時間）",
        "interval_jitter_label": "間隔隨機（± 秒）",
        "interval_jitter_hint": "0 ＝ 關閉；每次閒置間隔為基準 ± 此值（秒）· 0–{max}",
        "motion_pattern_label": "移動路徑",
        "motion_pattern_line": "直線",
        "motion_pattern_circle": "圓形",
        "motion_pattern_square": "方形",
        "pixels_label": "位移（像素）",
        "pixels_hint": "直線＝左右再還原；圓＝半徑；方＝邊長 · {lo}–{hi}",
        "path_speed_label": "路徑速度",
        "path_speed_hint": "幾何路徑繪製快慢 · {lo}–{hi}（數字愈大愈快）",
        "log_start_fail_path_speed": "開始失敗：路徑速度無效。",
        "err_path_speed": "請輸入有效路徑速度（整數，{lo}–{hi}）。",
        "status_motion_burst": "狀態：執行中 · 持續微動 · 約 {cd}",
        "btn_start": "開始",
        "btn_stop": "停止",
        "tray_checkbox": "關閉視窗時縮到系統匣（排程繼續）",
        "tray_switch_title": "關閉視窗時縮到系統匣",
        "tray_switch_hint": "啟用後關閉視窗將保留排程並在背景執行，可從系統匣圖示還原視窗。",
        "schedule_window_title": "上班時段（週一至週五）",
        "schedule_window_start_label": "開始",
        "schedule_window_end_label": "結束",
        "schedule_window_hint": "本機 24 小時制 HH:MM；支援多段（用逗號分隔，如 09:00-12:00,13:00-18:00,21:00-23:00），預設平日；可於 config 啟用週末與 cron-like。",
        "schedule_banner_active": "排程時段：{start}–{end}（本機；結束不含）· 週末：{weekend} · cron：{cron}",
        "schedule_banner_need_valid_times": "排程已開啟：請設定有效時段（HH:MM-HH:MM，可多段），且各段不可重疊。",
        "err_schedule_bounds": "請輸入有效排程：多段 HH:MM-HH:MM（可逗號分隔、不重疊）；cron-like 欄位若有值也需合法。",
        "log_start_fail_schedule_bounds": "開始失敗：上班時段時間無效。",
        "status_schedule_wait": "狀態：排程暫停 · 下次上班時段約 {cd}",
        "log_start_schedule": "已啟用排程：基礎時段 {start}–{end}（本機）· 週末：{weekend} · cron：{cron}。",
        "log_schedule_resumed": "已回到上班時段內，排程續行。",
        "schedule_weekend_on": "啟用",
        "schedule_weekend_off": "停用",
        "schedule_cron_off": "未設定",
        "tray_no_pystray": "（未安裝 pystray）",
        "status_stopped": "狀態：已停止",
        "status_running_min": "狀態：執行中 · 鍵盤／滑鼠無輸入達 {v:g} 分鐘後微動 · 下次約 {cd}",
        "status_running_sec": "狀態：執行中 · 鍵盤／滑鼠無輸入達 {v:g} 秒後微動 · 下次約 {cd}",
        "log_title": "活動紀錄",
        "log_ready": "程式已就緒。",
        "log_start_fail_interval": "開始失敗：間隔設定無效。",
        "log_start_fail_pixels": "開始失敗：位移設定無效。",
        "log_started_min": "已開始，鍵盤／滑鼠無輸入達 {v:g} 分鐘（約 {sec:.0f} 秒）後微動、路徑 {pat}、位移 {px} px、路徑速度 {ps}。",
        "log_started_min_jitter": "已開始，鍵盤／滑鼠無輸入約 {v:g} 分鐘（基準 ~{sec:.0f} 秒）、±{j:g} 秒隨機間隔、路徑 {pat}、位移 {px} px、路徑速度 {ps}。",
        "log_started_sec": "已開始，鍵盤／滑鼠無輸入達 {v:g} 秒後微動、路徑 {pat}、位移 {px} px、路徑速度 {ps}。",
        "log_started_sec_jitter": "已開始，鍵盤／滑鼠無輸入約 {v:g} 秒（基準）、±{j:g} 秒隨機間隔、路徑 {pat}、位移 {px} px、路徑速度 {ps}。",
        "log_stopped": "已手動停止。",
        "log_nudge": "已執行游標微動。",
        "log_nudge_zero": "已觸發排程（位移 0，未移動游標）。",
        "log_nudge_fail": "微動失敗：{err}",
        "log_exit": "結束程式。",
        "log_tray_minimize": "已縮至系統匣（排程仍執行，可從圖示還原或結束）。",
        "err_title": "輸入錯誤",
        "err_minutes": "請輸入有效的分鐘數（數字，且 ≥ {min}）。",
        "err_seconds": "請輸入有效的秒數（數字，且 ≥ {min}）。",
        "err_jitter": "請輸入有效的隨機秒數（數字，0–{max}）。",
        "log_start_fail_jitter": "開始失敗：間隔隨機設定無效。",
        "err_pixels": "請輸入有效的位移像素（整數，{lo}–{hi}）。",
        "tray_show": "顯示主視窗",
        "tray_quit": "結束程式",
        "nav_home": "首頁",
        "nav_settings": "設定",
        "nav_analytics": "分析",
        "settings_title": "設定",
        "btn_open_config_file": "開啟設定檔",
        "open_config_path_only": "此環境無法以預設程式開啟檔案。設定檔路徑：\n{path}",
        "err_open_config_file": "無法開啟或建立設定檔：{err}",
        "analytics_title": "分析",
        "analytics_subtitle": "Matplotlib 圖表（依本機 analytics.json 累計）；下方紀錄與首頁「紀錄」同步。",
        "analytics_chart_triggers": "觸發次數",
        "analytics_range_today": "今日",
        "analytics_range_week": "最近 7 天",
        "analytics_chart_runtime": "每日運作時長",
        "analytics_chart_patterns": "路徑使用比例（累計）",
        "analytics_axis_hour": "小時（0–23）",
        "analytics_axis_day": "日期",
        "analytics_axis_count": "次數",
        "analytics_axis_runtime_min": "分鐘",
        "analytics_empty": "尚無資料 — 請開始排程並觸發微動。",
        "intro_title": "歡迎使用",
        "motion_pattern_log_line": "直線",
        "motion_pattern_log_circle": "圓形",
        "motion_pattern_log_square": "方形",
        "intro_body": "try-working-hard {version}\n\n"
        "本程式會在鍵盤與滑鼠皆無輸入達您設定的時間後，以直線、圓形或方形路徑微量移動游標再還原，可用於簡報或閱讀時避免螢幕休眠（Windows 以系統閒置時間為準）。\n\n"
        "請僅在合法、符合公司／學校規定與服務條款的前提下使用；勿用於規避安全或監控機制。\n\n"
        "按 F1 可開啟鍵盤與無障礙說明。您的偏好設定會儲存在本機，下次開啟時自動載入。\n\n"
        "點選「確定」後不會再顯示本視窗（除非刪除設定檔）。",
        "a11y_help_title": "鍵盤與無障礙說明",
        "a11y_help_body": "try-working-hard {version}\n\n"
        "鍵盤：\n"
        "· F1 本說明\n"
        "· F2 / F3 / F4 首頁、設定、分析\n"
        "· F5 開始（首頁「控制面板」且可開始時）\n"
        "· Shift+F5 停止\n"
        "· Enter 開始、Esc 停止（僅主視窗顯示時；條件同 F5／Shift+F5）\n"
        "· F6 首頁切換「控制面板」/「紀錄」\n\n"
        "可點擊「間隔」「間隔隨機」「位移」「路徑速度」或「移動路徑」標籤，將焦點移到該欄位。間隔可選「分鐘」或「秒」；「間隔」指鍵盤與滑鼠皆無輸入需累積的時間（與主控台狀態列、Windows 系統閒置時間一致）。欄位下方有 30s／1m／5m／10m 快速按鈕。\n\n"
        "注意：CustomTkinter 多數控制項以畫布繪製，部分螢幕閱讀器可能無法宣讀所有元件。視窗標題與本對話框採用系統標準外觀。",
    },
    "en": {
        "window_title": "try-working-hard",
        "app_subtitle": "",
        "seg_control": "Control",
        "seg_log": "Log",
        "theme_appearance": "Appearance",
        "theme_appearance_dark": "Dark",
        "theme_appearance_light": "Light",
        "theme_status_dark": "Dark theme",
        "theme_status_light": "Light theme",
        "lang_ui": "Language",
        "dashboard": "Dashboard",
        "interval_label": "Interval",
        "interval_presets_caption": "Quick presets",
        "interval_preset_30s": "30s",
        "interval_preset_1m": "1m",
        "interval_preset_5m": "5m",
        "interval_preset_10m": "10m",
        "autostart_switch_title": "Start with Windows",
        "autostart_switch_hint": "Run at sign-in and start in the system tray on supported setups.",
        "autostart_not_windows": " (Windows only.)",
        "autostart_requires_tray": " (pystray required.)",
        "log_tray_start_hidden": "Running from the tray (main window hidden).",
        "interval_unit_min": "min",
        "interval_unit_sec": "sec",
        "interval_hint_min": "≥ 0.1, decimals — min idle (no keyboard/mouse) before nudge",
        "interval_hint_sec": "≥ 6, decimals — min idle (no keyboard/mouse) before nudge",
        "interval_jitter_label": "Interval jitter (± sec)",
        "interval_jitter_hint": "0 = off; each idle spacing is base interval ± this many seconds · 0–{max}",
        "motion_pattern_label": "Path",
        "motion_pattern_line": "Line",
        "motion_pattern_circle": "Circle",
        "motion_pattern_square": "Square",
        "pixels_label": "Nudge (pixels)",
        "pixels_hint": "Line: horizontal; circle: radius; square: edge · {lo}–{hi}",
        "path_speed_label": "Path speed",
        "path_speed_hint": "How fast to trace the path · {lo}–{hi} (higher = faster)",
        "log_start_fail_path_speed": "Start failed: invalid path speed.",
        "err_path_speed": "Enter a valid path speed (integer, {lo}–{hi}).",
        "status_motion_burst": "Status: running · active motion · ~{cd} left",
        "btn_start": "Start",
        "btn_stop": "Stop",
        "tray_checkbox": "Close to system tray (schedule continues)",
        "tray_switch_title": "Minimize to system tray on close",
        "tray_switch_hint": "When enabled, closing the window keeps the schedule running; restore from the tray icon.",
        "schedule_window_title": "Schedule window (weekdays)",
        "schedule_window_start_label": "Start",
        "schedule_window_end_label": "End",
        "schedule_window_hint": "Local 24h HH:MM; supports multi-segment windows (comma-separated, e.g. 09:00-12:00,13:00-18:00,21:00-23:00). Weekends and cron-like rules are available in config.",
        "schedule_banner_active": "Schedule: {start}–{end} local (end exclusive) · weekends: {weekend} · cron: {cron}",
        "schedule_banner_need_valid_times": "Schedule on: enter valid windows as HH:MM-HH:MM (comma-separated allowed, no overlaps).",
        "err_schedule_bounds": "Enter a valid schedule: HH:MM-HH:MM windows (comma-separated, non-overlapping); cron-like expressions must also be valid if set.",
        "log_start_fail_schedule_bounds": "Start failed: invalid schedule window times.",
        "status_schedule_wait": "Status: schedule paused · resuming in ~{cd}",
        "log_start_schedule": "Schedule enabled: base window {start}–{end} (local), weekends: {weekend}, cron: {cron}.",
        "log_schedule_resumed": "Back within work hours; schedule continues.",
        "schedule_weekend_on": "on",
        "schedule_weekend_off": "off",
        "schedule_cron_off": "none",
        "tray_no_pystray": "(pystray not installed)",
        "status_stopped": "Status: stopped",
        "status_running_min": "Status: running · nudge after {v:g} min idle (keyboard/mouse) · next in {cd}",
        "status_running_sec": "Status: running · nudge after {v:g} s idle (keyboard/mouse) · next in {cd}",
        "log_title": "Activity log",
        "log_ready": "Ready.",
        "log_start_fail_interval": "Start failed: invalid interval.",
        "log_start_fail_pixels": "Start failed: invalid nudge size.",
        "log_started_min": "Started: nudge after {v:g} min (~{sec:.0f} s) with no keyboard/mouse input, path {pat}, nudge {px} px, path speed {ps}.",
        "log_started_min_jitter": "Started: nudge after ~{v:g} min base (~{sec:.0f} s idle) with ±{j:g} s jitter between waits, path {pat}, nudge {px} px, path speed {ps}.",
        "log_started_sec": "Started: nudge after {v:g} s with no keyboard/mouse input, path {pat}, nudge {px} px, path speed {ps}.",
        "log_started_sec_jitter": "Started: nudge after ~{v:g} s base idle with ±{j:g} s jitter between waits, path {pat}, nudge {px} px, path speed {ps}.",
        "log_stopped": "Stopped manually.",
        "log_nudge": "Cursor nudge executed.",
        "log_nudge_zero": "Tick fired (0 px — cursor not moved).",
        "log_nudge_fail": "Nudge failed: {err}",
        "log_exit": "Exiting.",
        "log_tray_minimize": "Minimized to tray (schedule still running).",
        "err_title": "Invalid input",
        "err_minutes": "Enter a valid interval in minutes (number, ≥ {min}).",
        "err_seconds": "Enter a valid interval in seconds (number, ≥ {min}).",
        "err_jitter": "Enter a valid jitter in seconds (number, 0–{max}).",
        "log_start_fail_jitter": "Start failed: invalid interval jitter.",
        "err_pixels": "Enter a valid nudge size (integer, {lo}–{hi}).",
        "tray_show": "Show window",
        "tray_quit": "Quit",
        "nav_home": "Home",
        "nav_settings": "Settings",
        "nav_analytics": "Analytics",
        "settings_title": "Settings",
        "btn_open_config_file": "Open config file",
        "open_config_path_only": "This platform has no default “open with” for files. Config path:\n{path}",
        "err_open_config_file": "Could not open or create the config file: {err}",
        "analytics_title": "Analytics",
        "analytics_subtitle": "Matplotlib charts from local aggregates (analytics.json). Log stays synced with Home → Log.",
        "analytics_chart_triggers": "Nudge counts",
        "analytics_range_today": "Today",
        "analytics_range_week": "Last 7 days",
        "analytics_chart_runtime": "Scheduled uptime per day",
        "analytics_chart_patterns": "Path usage (totals)",
        "analytics_axis_hour": "Hour (0–23)",
        "analytics_axis_day": "Date",
        "analytics_axis_count": "Count",
        "analytics_axis_runtime_min": "Minutes",
        "analytics_empty": "No data yet — start the schedule and generate nudges.",
        "intro_title": "Welcome",
        "motion_pattern_log_line": "line",
        "motion_pattern_log_circle": "circle",
        "motion_pattern_log_square": "square",
        "intro_body": "try-working-hard {version}\n\n"
        "This app nudges the cursor only after the interval elapses with no keyboard or mouse input, along a line, circle, or square path, then restores it—useful to keep the screen awake while presenting or reading (on Windows, idle time uses the system last-input time).\n\n"
        "Use it only in lawful ways that comply with employer, school, and service rules; do not use it to bypass security or monitoring.\n\n"
        "Press F1 for keyboard and accessibility help. Your preferences are saved locally and loaded next time.\n\n"
        "You will not see this dialog again after you click OK (unless you delete the config file).",
        "a11y_help_title": "Keyboard and accessibility",
        "a11y_help_body": "try-working-hard {version}\n\n"
        "Keyboard:\n"
        "· F1  this help\n"
        "· F2 / F3 / F4  Home, Settings, Analytics\n"
        "· F5  Start (Home → Control, when available)\n"
        "· Shift+F5  Stop\n"
        "· Enter / Esc  Start / Stop (main window visible only; same rules as F5 / Shift+F5)\n"
        "· F6  Home: toggle Control / Log\n\n"
        "Click the Interval, Interval jitter, Nudge (pixels), Path speed, or Path label to move focus to that field. Choose min or sec for the interval: Interval is the required idle time with no keyboard or mouse input before a nudge (status line uses the same idle time as Windows GetLastInputInfo). Use 30s / 1m / 5m / 10m under the field for a quick set.\n\n"
        "Note: CustomTkinter draws most controls on a canvas, so not every control is exposed to all screen readers. The window title and this dialog use standard toolkit UIs.\n"
        "Tab / Shift+Tab move focus; tooltips are not used for the canvas controls.",
    },
}
